/// 京杭大运河声景数据模型
class CanalSoundscapeData {
  final String id;
  final String title;
  final String period;
  final String location;
  final double latitude;
  final double longitude;
  final String poem;
  final String poemAuthor;
  final String emotion;
  final String audioUrl;
  final String imageUrl;
  final String description;
  final bool isHistorical;

  CanalSoundscapeData({
    required this.id,
    required this.title,
    required this.period,
    required this.location,
    required this.latitude,
    required this.longitude,
    required this.poem,
    required this.poemAuthor,
    required this.emotion,
    required this.audioUrl,
    required this.imageUrl,
    required this.description,
    required this.isHistorical,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'title': title,
      'period': period,
      'location': location,
      'latitude': latitude,
      'longitude': longitude,
      'poem': poem,
      'poemAuthor': poemAuthor,
      'emotion': emotion,
      'audioUrl': audioUrl,
      'imageUrl': imageUrl,
      'description': description,
      'isHistorical': isHistorical,
    };
  }

  factory CanalSoundscapeData.fromMap(Map<String, dynamic> map) {
    return CanalSoundscapeData(
      id: map['id'],
      title: map['title'],
      period: map['period'],
      location: map['location'],
      latitude: map['latitude'],
      longitude: map['longitude'],
      poem: map['poem'],
      poemAuthor: map['poemAuthor'],
      emotion: map['emotion'],
      audioUrl: map['audioUrl'],
      imageUrl: map['imageUrl'],
      description: map['description'],
      isHistorical: map['isHistorical'],
    );
  }
}

/// 京杭大运河声景数据集
class CanalSoundscapeDataset {
  static final List<CanalSoundscapeData> soundscapes = [
    // 北京段
    CanalSoundscapeData(
      id: '1',
      title: '通州码头晨钟',
      period: '明代',
      location: '北京通州',
      latitude: 39.9042,
      longitude: 116.6591,
      poem: '舳舻衔尾浮清波，千帆竞发通州河',
      poemAuthor: '杨基',
      emotion: '繁忙',
      audioUrl: 'assets/audio/soundscapes/01_tongzhou_wharf.mp3',
      imageUrl: 'assets/images/soundscapes/tongzhou_wharf.jpg',
      description: '明代通州码头是京杭大运河的重要起点，每日清晨钟声响起，商船云集',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '2',
      title: '什刹海夜市',
      period: '清代',
      location: '北京什刹海',
      latitude: 39.9369,
      longitude: 116.3875,
      poem: '银锭桥西十里秋，满湖明月照琼楼',
      poemAuthor: '纪晓岚',
      emotion: '热闹',
      audioUrl: 'assets/audio/soundscapes/02_shichahai_night.mp3',
      imageUrl: 'assets/images/soundscapes/shichahai_night.jpg',
      description: '清代什刹海夜市灯火通明，商贾云集，运河繁华景象',
      isHistorical: true,
    ),

    // 天津段
    CanalSoundscapeData(
      id: '3',
      title: '天津三岔口',
      period: '明代',
      location: '天津三岔河口',
      latitude: 39.1422,
      longitude: 117.1767,
      poem: '三岔河口水云乡，舳舻千里泛晨光',
      poemAuthor: '王士祯',
      emotion: '壮阔',
      audioUrl: 'assets/audio/soundscapes/03_tianjin_sancha.mp3',
      imageUrl: 'assets/images/soundscapes/tianjin_sancha.jpg',
      description: '明代天津三岔河口，南北运河交汇处，船只往来如织',
      isHistorical: true,
    ),

    // 河北段
    CanalSoundscapeData(
      id: '4',
      title: '沧州铁狮吼',
      period: '北宋',
      location: '河北沧州',
      latitude: 38.3037,
      longitude: 116.8385,
      poem: '铁狮临运河，千年守沧州',
      poemAuthor: '民谣',
      emotion: '雄浑',
      audioUrl: 'assets/audio/soundscapes/04_cangzhou_lion.mp3',
      imageUrl: 'assets/images/soundscapes/cangzhou_lion.jpg',
      description: '北宋沧州铁狮，镇守运河要道，风声如狮吼',
      isHistorical: true,
    ),

    // 山东段
    CanalSoundscapeData(
      id: '5',
      title: '德州扒鸡香',
      period: '清代',
      location: '山东德州',
      latitude: 37.4513,
      longitude: 116.3594,
      poem: '德州驿站客如云，扒鸡美名传九州',
      poemAuthor: '民谣',
      emotion: '温馨',
      audioUrl: 'assets/audio/soundscapes/05_dezhou_station.mp3',
      imageUrl: 'assets/images/soundscapes/dezhou_station.jpg',
      description: '清代德州是运河重要驿站，扒鸡闻名天下',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '6',
      title: '东昌府夜雨',
      period: '明代',
      location: '山东聊城',
      latitude: 36.4570,
      longitude: 115.9856,
      poem: '夜雨东昌府，客船听雨眠',
      poemAuthor: '民谣',
      emotion: '静谧',
      audioUrl: 'assets/audio/soundscapes/06_liaocheng_rain.mp3',
      imageUrl: 'assets/images/soundscapes/liaocheng_rain.jpg',
      description: '明代东昌府，运河边夜雨绵绵，船客听雨',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '7',
      title: '济宁竹竿巷',
      period: '明代',
      location: '山东济宁',
      latitude: 35.4155,
      longitude: 116.5873,
      poem: '竹竿巷口市声喧，百货云集济宁城',
      poemAuthor: '民谣',
      emotion: '繁华',
      audioUrl: 'assets/audio/soundscapes/07_jining_bamboo.mp3',
      imageUrl: 'assets/images/soundscapes/jining_bamboo.jpg',
      description: '明代济宁竹竿巷，运河商业中心，市声鼎沸',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '8',
      title: '徐州黄河渡',
      period: '明代',
      location: '江苏徐州',
      latitude: 34.2044,
      longitude: 117.2857,
      poem: '黄河入运河，波涛声如雷',
      poemAuthor: '民谣',
      emotion: '壮阔',
      audioUrl: 'assets/audio/soundscapes/08_xuzhou_ferry.mp3',
      imageUrl: 'assets/images/soundscapes/xuzhou_ferry.jpg',
      description: '明代徐州，黄河与运河交汇，波涛汹涌',
      isHistorical: true,
    ),

    // 江苏段
    CanalSoundscapeData(
      id: '9',
      title: '宿迁古镇雨',
      period: '清代',
      location: '江苏宿迁',
      latitude: 33.9631,
      longitude: 118.2752,
      poem: '宿迁古镇听雨声，渔歌互答运河中',
      poemAuthor: '民谣',
      emotion: '静谧',
      audioUrl: 'assets/audio/soundscapes/09_suqian_town.mp3',
      imageUrl: 'assets/images/soundscapes/suqian_town.jpg',
      description: '清代宿迁古镇，烟雨蒙蒙，渔歌悠扬',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '10',
      title: '淮安漕运署',
      period: '明代',
      location: '江苏淮安',
      latitude: 33.5975,
      longitude: 119.0153,
      poem: '漕运总督署前站，南船北马汇淮安',
      poemAuthor: '民谣',
      emotion: '威严',
      audioUrl: 'assets/audio/soundscapes/10_huaian_caoyun.mp3',
      imageUrl: 'assets/images/soundscapes/huaian_caoyun.jpg',
      description: '明代淮安，漕运总督署所在，官船往来',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '11',
      title: '扬州二十四桥',
      period: '唐代',
      location: '江苏扬州',
      latitude: 32.3912,
      longitude: 119.4120,
      poem: '二十四桥明月夜，玉人何处教吹箫',
      poemAuthor: '杜牧',
      emotion: '浪漫',
      audioUrl: 'assets/audio/soundscapes/11_yangzhou_bridge.mp3',
      imageUrl: 'assets/images/soundscapes/yangzhou_bridge.jpg',
      description: '唐代扬州二十四桥，月夜箫声，千古绝唱',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '12',
      title: '扬州瘦西湖晨',
      period: '清代',
      location: '江苏扬州',
      latitude: 32.4102,
      longitude: 119.4392,
      poem: '瘦西湖畔柳如烟，画舫往来似神仙',
      poemAuthor: '郑板桥',
      emotion: '清幽',
      audioUrl: 'assets/audio/soundscapes/12_yangzhou_shouxi.mp3',
      imageUrl: 'assets/images/soundscapes/yangzhou_shouxi.jpg',
      description: '清代扬州瘦西湖，晨曦鸟鸣，画舫摇橹',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '13',
      title: '镇江金山寺钟',
      period: '宋代',
      location: '江苏镇江',
      latitude: 32.2082,
      longitude: 119.4292,
      poem: '金山寺里钟声起，长江运河共悠扬',
      poemAuthor: '苏轼',
      emotion: '悠远',
      audioUrl: 'assets/audio/soundscapes/13_zhenjiang_jinshan.mp3',
      imageUrl: 'assets/images/soundscapes/zhenjiang_jinshan.jpg',
      description: '宋代镇江金山寺，钟声回荡江河之间',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '14',
      title: '常州天宁寺',
      period: '明代',
      location: '江苏常州',
      latitude: 31.7728,
      longitude: 119.9425,
      poem: '天宁寺塔耸云霄，运河晚照映红绡',
      poemAuthor: '民谣',
      emotion: '禅意',
      audioUrl: 'assets/audio/soundscapes/14_changzhou_tianning.mp3',
      imageUrl: 'assets/images/soundscapes/changzhou_tianning.jpg',
      description: '明代常州天宁寺，晚归船只伴诵经声',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '15',
      title: '无锡鼋头渚',
      period: '明代',
      location: '江苏无锡',
      latitude: 31.5411,
      longitude: 120.2071,
      poem: '鼋头渚上看太湖，运河入湖天水阔',
      poemAuthor: '民谣',
      emotion: '开阔',
      audioUrl: 'assets/audio/soundscapes/15_wuxi_yuantou.mp3',
      imageUrl: 'assets/images/soundscapes/wuxi_yuantou.jpg',
      description: '明代无锡鼋头渚，太湖烟波浩渺',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '16',
      title: '苏州寒山寺钟',
      period: '唐代',
      location: '江苏苏州',
      latitude: 31.3123,
      longitude: 120.5955,
      poem: '姑苏城外寒山寺，夜半钟声到客船',
      poemAuthor: '张继',
      emotion: '空灵',
      audioUrl: 'assets/audio/soundscapes/16_suzhou_hanshan.mp3',
      imageUrl: 'assets/images/soundscapes/suzhou_hanshan.jpg',
      description: '唐代苏州寒山寺，夜半钟声千古传颂',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '17',
      title: '苏州平江路',
      period: '明代',
      location: '江苏苏州',
      latitude: 31.3192,
      longitude: 120.6219,
      poem: '平江路上听评弹，小桥流水人家欢',
      poemAuthor: '民谣',
      emotion: '温婉',
      audioUrl: 'assets/audio/soundscapes/17_suzhou_pingjiang.mp3',
      imageUrl: 'assets/images/soundscapes/suzhou_pingjiang.jpg',
      description: '明代苏州平江路，评弹声声，小桥流水',
      isHistorical: true,
    ),

    // 浙江段
    CanalSoundscapeData(
      id: '18',
      title: '嘉兴南湖烟雨',
      period: '明代',
      location: '浙江嘉兴',
      latitude: 30.7481,
      longitude: 120.7568,
      poem: '南湖烟雨迷朦胧，渔舟唱晚运河中',
      poemAuthor: '民谣',
      emotion: '朦胧',
      audioUrl: 'assets/audio/soundscapes/18_jiaxing_nanhu.mp3',
      imageUrl: 'assets/images/soundscapes/jiaxing_nanhu.jpg',
      description: '明代嘉兴南湖，烟雨蒙蒙，渔歌悠扬',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '19',
      title: '湖州丝绸市',
      period: '宋代',
      location: '浙江湖州',
      latitude: 30.8703,
      longitude: 120.0933,
      poem: '湖丝名扬天下知，运河商船载锦绮',
      poemAuthor: '民谣',
      emotion: '繁华',
      audioUrl: 'assets/audio/soundscapes/19_huzhou_silk.mp3',
      imageUrl: 'assets/images/soundscapes/huzhou_silk.jpg',
      description: '宋代湖州丝绸市场，商贾云集，繁华无比',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '20',
      title: '杭州拱宸桥',
      period: '明代',
      location: '浙江杭州',
      latitude: 30.3260,
      longitude: 120.1345,
      poem: '拱宸桥下水悠悠，千年运河到杭州',
      poemAuthor: '民谣',
      emotion: '沧桑',
      audioUrl: 'assets/audio/soundscapes/20_hangzhou_gongchen.mp3',
      imageUrl: 'assets/images/soundscapes/hangzhou_gongchen.jpg',
      description: '明代杭州拱宸桥，运河终点，千年沧桑',
      isHistorical: true,
    ),
    CanalSoundscapeData(
      id: '21',
      title: '杭州西湖晨曦',
      period: '宋代',
      location: '浙江杭州',
      latitude: 30.2503,
      longitude: 120.1483,
      poem: '欲把西湖比西子，淡妆浓抹总相宜',
      poemAuthor: '苏轼',
      emotion: '清新',
      audioUrl: 'assets/audio/soundscapes/21_hangzhou_xihu.mp3',
      imageUrl: 'assets/images/soundscapes/hangzhou_xihu.jpg',
      description: '宋代杭州西湖，晨曦鸟鸣，美如画卷',
      isHistorical: true,
    ),

    // 现代声景
    CanalSoundscapeData(
      id: '22',
      title: '现代通州运河公园',
      period: '当代',
      location: '北京通州',
      latitude: 39.9042,
      longitude: 116.6591,
      poem: '通州新貌展风华，运河公园美如画',
      poemAuthor: '现代',
      emotion: '活力',
      audioUrl: 'assets/audio/soundscapes/22_modern_tongzhou.mp3',
      imageUrl: 'assets/images/soundscapes/modern_tongzhou.jpg',
      description: '现代通州运河公园，市民休闲健身的好去处',
      isHistorical: false,
    ),
    CanalSoundscapeData(
      id: '23',
      title: '现代扬州瘦西湖',
      period: '当代',
      location: '江苏扬州',
      latitude: 32.4102,
      longitude: 119.4392,
      poem: '瘦西湖畔游人如织，运河文化焕发新生',
      poemAuthor: '现代',
      emotion: '繁荣',
      audioUrl: 'assets/audio/soundscapes/23_modern_yangzhou.mp3',
      imageUrl: 'assets/images/soundscapes/modern_yangzhou.jpg',
      description: '现代扬州瘦西湖，游客如织，繁荣景象',
      isHistorical: false,
    ),
    CanalSoundscapeData(
      id: '24',
      title: '现代杭州运河夜景',
      period: '当代',
      location: '浙江杭州',
      latitude: 30.3260,
      longitude: 120.1345,
      poem: '运河夜景灯火辉煌，音乐喷泉舞翩跹',
      poemAuthor: '现代',
      emotion: '璀璨',
      audioUrl: 'assets/audio/soundscapes/24_modern_hangzhou.mp3',
      imageUrl: 'assets/images/soundscapes/modern_hangzhou.jpg',
      description: '现代杭州运河夜景，灯光璀璨，音乐喷泉',
      isHistorical: false,
    ),
  ];
}
